using System;
using Microsoft.CodeAnalysis;
using Utilities;

namespace ED.DOTS.EntitiesEvents.SourceGenerator
{
    [Generator]
    public class SourceGenerator : ISourceGenerator
    {
        private FileLogger Logger { get; } = new FileLogger("EntitiesEvents");

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var helper = new CodeBuildHelper(context.Compilation);
            var assemblyAttributes = context.Compilation.Assembly.GetAttributes();

            foreach (var attribute in assemblyAttributes)
            {
                try
                {
                    if (!helper.IsRegistrationAttribute(attribute))
                        continue;

                    if (attribute.ConstructorArguments.Length != 1)
                    {
                        Logger.Error($"{GetType().Name}: Attribute arguments length is not 1.");
                        continue;
                    }

                    var ctorArg = attribute.ConstructorArguments[0];
                    if (!(ctorArg.Value is INamedTypeSymbol typeSymbol))
                    {
                        Logger.Error($"{GetType().Name}: Attribute argument is not a type symbol.");
                        continue;
                    }

                    var eventTypeName = typeSymbol.Name;
                    var eventTypeNamespace = typeSymbol.ContainingNamespace?.ToString();

                    GenerateCode(eventTypeName, eventTypeNamespace, out var fileName, out var sourceCode);
                    context.AddSource(fileName, sourceCode);
                    Logger.Info($"{GetType().Name}: Generated source {fileName}");
                }
                catch (Exception e)
                {
                    Logger.Error(e.ToString());
                }
            }
        }

        private static void GenerateCode(string eventTypeName, string eventTypeNamespace, out string fileName, out string sourceCode)
        {
            var fullTypeName = string.IsNullOrWhiteSpace(eventTypeNamespace) ? eventTypeName : $"{eventTypeNamespace}.{eventTypeName}";
            fileName = $"{eventTypeName}_EventSystem.g.cs";

            sourceCode = $@"// <auto-generated/>
using Unity.Entities;
using ED.DOTS.EntitiesEvents;

[assembly: RegisterGenericComponentType(typeof(EventSingleton<{fullTypeName}>))]

{(string.IsNullOrWhiteSpace(eventTypeNamespace) ? "" : $@"namespace {eventTypeNamespace}
{{")}
    partial class {eventTypeName}_EventSystem : EventSystemBase<{fullTypeName}> {{ }}
{(string.IsNullOrWhiteSpace(eventTypeNamespace) ? "" : $@"
}}")}
";
        }
    }
}